config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'lists#about'
  resources :lists, only: %i[index show create new destroy] do
    collection do
      get :search, as: :search
    end

    resources :bookmarks, only: %i[new create] do
      resources :comments, only: %i[new create]
    end
  end
  resources :bookmarks, only: :destroy
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
# frozen_string_literal: true

class Bookmark < ApplicationRecord
  belongs_to :movie
  has_many :comments, dependent: :destroy
  belongs_to :list
  validates_uniqueness_of :movie_id, scope: :list_id
  validates :comment, length: { minimum: 6 }
  validates_presence_of :movie_id, :list_id
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :bookmark
end

app/models/list.rb
# frozen_string_literal: true

class List < ApplicationRecord
  has_one_attached :photo
  has_many :bookmarks
  has_many :movies, through: :bookmarks, dependent: :destroy

  validates :name, uniqueness: {case_sensitive: false}, presence: true

end

app/models/movie.rb
# frozen_string_literal: true

class Movie < ApplicationRecord
  has_many :bookmarks

  validates_presence_of :title, :overview
  validates :title, uniqueness: true
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController

  def new
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @list = List.find(params[:list_id])
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :list_path
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@bookmark.list)
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @comment = Comment.new
  end

  def create
    @comment = Comment.new(comment_params)
    @comment.bookmark = Bookmark.find(params[:bookmark_id])
    if @comment.save
      redirect_to list_path(@comment.bookmark.list)
    else
      render list_path(@comment.bookmark.list)
    end
  end


  private

  def comment_params
    params.require(:comment).permit(:body, :rating)
  end
end

app/controllers/lists_controller.rb
# frozen_string_literal: true

class ListsController < ApplicationController

  def about
  end

  def index
    @lists = List.all
    @images = Dir.entries('app/assets/images')
    @list = List.new
  end

  def show
    @list = List.find(params[:id])
    @bookmark = Bookmark.new
    @comment = Comment.new

  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to lists_path
    else
      render :new
    end
  end

   def search
    @results = List.where('lower(name) LIKE ?', "%#{params[:name].downcase}%")
    @results = if params[:name].empty?
                 @message = "You didn't enter anything!"
                 zero_results
               elsif @results.count.zero?
                 @message = "No results for #{params[:name]}."
                 zero_results
               else
                 @count = @results.count
                 @message = "Here are all the results for #{params[:name]}:"
                 List.where('name LIKE ?', "%#{params[:name]}%")

               end
  end

  private

  def zero_results
    @count = 0
    []
  end

  def list_params
    params.require(:list).permit(:name, :photo)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
# frozen_string_literal: true

module BookmarksHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/lists_helper.rb
# frozen_string_literal: true

module ListsHelper
end

app/helpers/movies_helper.rb
# frozen_string_literal: true

module MoviesHelper
end

app/views/bookmarks/_form.html.erb
<!-- On show.html.erb -->

<%= simple_form_for [list, bookmark] do |f| %>
<%= f.association :movie %>

<%= f.input :comment, as: :text %>
<%= f.button :submit, class: "btn btn-primary" %>
<% end %>

app/views/comments/_form.html.erb
<%= simple_form_for[bookmark, comment] do |f| %>
<%= f.input :body %>
<%= f.input :rating %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Watch List | Lists</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="The best way to list and share opinions on movies.">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>
  <body>
    <%= render "/shared/navbar" %>
    <%= yield %>
    <%= render "/shared/footer" %>
  </body>
</html>

app/views/lists/about.html.erb
<%= render "lists/components/home_banner" %>
<div class="container">
  <div class="row">
    <div class="col-1">
      <%= image_tag "", alt: "alttext" %>
    </div>
    <div class="col landing-desc-border">
      Add your favorite movies
    </div>
  </div>

  <hr>

   <div class="row">
    <div class="col">
      One of three columns
    </div>
    <div class="col">
      One of three columns
    </div>
  </div>


  <hr>

<!-- for face detection -->

app/views/lists/components/_banner.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,1),rgba(0,0,0,0), rgba(0,0,0,0), rgba(0,0,0,0), rgba(0,0,0,0), rgba(0,0,0,1)) , url(https://images.unsplash.com/photo-1535016120720-40c646be5580?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1650&q=80);">
  <div class="container">
    <h1>Add a new list</h1>
  </div>
</div>

app/views/lists/components/_form.html.erb
<!-- On /index.html.erb -->

<%= simple_form_for(list) do |f| %>
<%= f.input :photo, as: :file, label: "Upload a photo for your list." %>
<%= f.input :name, input_html: {class: 'mr-sm2 round-search'}, label: false, placeholder: "Add list" %>
<%= f.submit "Create List", class: "btn btn-primary btn-red" %>
<% end %>

app/views/lists/components/_home_banner.html.erb
<!-- On about.html.erb -->

<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,1),rgba(0,0,0,0), rgba(0,0,0,0), rgba(0,0,0,0), rgba(0,0,0,0), rgba(0,0,0,1)) , url(https://images.unsplash.com/photo-1585951237318-9ea5e175b891?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=2850&q=80);">
  <div class="container">
    <h1>Movie List</h1>
    <p>The only place to list movies</p>
  </div>
</div>

app/views/lists/components/_list_card.html.erb
<div class="row align-items-start">
  <% @lists.each do |list| %>
    <div class="col mb-3">
      <div class="card list-card" style="width: 18rem;">
        <%= link_to list_path(list) do %>
          <% if list.photo.attached? %>
          <%= cl_image_tag list.photo.key, class: 'card-img-top card-img', crop: :fill %>
          <% else %>
          <%= image_tag "https://source.unsplash.com/1600x900/?#{list.name.downcase}", alt: " List category: #{list.name}", class: 'card-img-top card-img' %>
          <% end %>
        <% end %>
        <div class="card-body list-card-body">
        <h5 class="card-title list-card-title"><%= link_to list.name, list_path(list) %></h5>
        <p class="card-text list-card-text">
        </p>
      </div>
      </div>
    </div>
  <% end %>
</div>

app/views/lists/index.html.erb
<!-- views/shared/lists/components/_list_card -->
<%= render "/shared/banner" %>

<div class="container">

<h2 class="mt-3 text-align-center">Lists</h2>


<!-- views/lists/components/_form.html.erb -->
<%= render "lists/components/form", list: @list%>

<hr>

<!-- views/lists/components/_list_card_html.erb -->
<%= render "lists/components/list_card" %>

</div>

app/views/lists/new.html.erb
<%= render "lists/components/banner" %>


<div class="container">
<div class="row justify-content-center">
<h2>Add the name of your list</h2>
</div>
<div class="row justify-content-center">
<div class="col-6">

<%= render "lists/components/form", list: @list %>
</div>
</div>
</div>

app/views/lists/search.html.erb
<div class="container">
  <h1>Search results</h1>

<%= @message %>

<% @results.each do |result| %>
  <% if  %>
    <% result.photo.attached? == false %>
     <%= link_to list_path(result) do %>
        <%= image_tag "https://source.unsplash.com/1600x900/?#{result.name.downcase}", alt: " List category: #{result.name}", class: 'card-img-top' %>
    <% end %>
    <% else %>
    <%= link_to list_path(result) do %>
    <%= cl_image_tag result.photo.key, class: 'card-img-top card-img', crop: :fill %>
    <% end %>
  <% end %>
  <%= result.name %>
<% end %>

</div>


<hr>

app/views/lists/show.html.erb
<%= render "lists/components/banner" %>
<div class="container">
  <h1> <%= @list.name %> </h1>
   <% if  %>
    <% @list.photo.attached? == false %>
     <%= link_to list_path(@list) do %>
        <%= image_tag "https://source.unsplash.com/1600x900/?#{@list.name.downcase}", alt: " List category: #{@list.name}", class: 'card-img-list' %>
    <% end %>
    <% else %>
    <%= link_to list_path(@list) do %>
    <%= cl_image_tag @list.photo.key, class: 'card-img-top card-img', crop: :fill %>
    <% end %>
  <% end %>
<hr>

<h3>Bookmarks</h3>
  <ul>
    <% @list.movies.each do |movie| %>
      <li>
        <%= image_tag movie.poster_url, alt: "Movie title: #{movie.title}", class: "bookmark-img" %>
        <%= movie.title %> |
        <% movie.bookmarks.each do |bookmark|%>
          <%= bookmark.comment %> |
          <%= link_to "Delete bookmark", bookmark_path(bookmark), method: :delete %>
          <% bookmark.comments.each do |comment| %>
          <%= comment.rating %>
          <% end %>
        <% end %>
      </li>
    <% end %>
  </ul>
  <hr>
  <h2>Add a bookmark</h2>
  <%= render "/bookmarks/form", list: @list, bookmark: @bookmark %>
</div>

app/views/shared/_banner.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1650&q=80);">
  <div class="container">
    <h1>List your favorite movies!</h1>
  </div>
</div>

app/views/shared/_footer.html.erb
<!-- <footer class="footer">
  <ul>
    <li>About</li>
    <li><i>Twitter</i></li>
    <li><i>Facebook</i></li>
    <li><i>LinkedIn</i></li>
    <li><i></i></li>
  </ul>
</footer>
 -->

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg  nv-black">
  <%= link_to "Movie List", root_path, class: "navbar-brand white" %>
  <button class="navbar-toggler white" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
<!--         <a class="nav-link" href="">Home <span class="sr-only">(current)</span></a>
 -->        <%= link_to "Home", lists_path, class: "nav-link"%>
      </li>
      <li class="nav-item">
        <%= link_to "Add list", new_list_path, class: 'nav-link'%>
      </li>

    </ul>
    <form class="form-inline my-2 my-lg-0" action="/lists/search" method="get">
      <input class="form-control mr-sm-2 round-search" value="<%= params[:name]%>" type="search" name="name" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success btn-red my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/shared/_search.html.erb
  <form class="form-inline my-2 my-lg-0" action="/lists/search" method="get">
      <input class="form-control mr-sm-2 round-search" value="<%= params[:name]%>" type="search" name="name" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success btn-red my-2 my-sm-0" type="submit">Search</button>
    </form>